# Meta data
name:         Ratchet
authors:      Connor Sears
description:  Build mobile apps with simple HTML, CSS, and JS components.

# Dependencies
pygments:     true

# Permalinks
permalink:    pretty

# Server
source:       docs
port:         4000
url:          http://goratchet.com
